import { Lesson } from "@shared/schema";

export const lessonData: Record<string, Lesson> = {
  lesson1: {
    title: "Lesson 1: Four Forces of Flight",
    subtitle: "Understanding Lift, Weight, Thrust, and Drag",
    flashcards: [
      { q: "What are the four forces of flight?", a: "Lift, Weight (Gravity), Thrust, and Drag" },
      { q: "Which force opposes weight?", a: "Lift - the upward force generated by the wing" },
      { q: "What creates drag?", a: "Air resistance opposing the aircraft's motion through the air" },
      { q: "How is thrust generated?", a: "By the propeller or jet engine pushing air backward" },
      { q: "What happens when lift equals weight?", a: "The aircraft maintains level flight with no vertical acceleration" },
      { q: "What must happen for an aircraft to climb?", a: "Lift must be greater than weight" },
      { q: "What are the two types of drag?", a: "Induced drag (created by lift) and parasitic drag (from air resistance)" },
      { q: "How does angle of attack affect lift?", a: "Increasing angle of attack increases lift up to the critical angle, then causes a stall" }
    ],
    quiz: {
      questions: [
        {
          question: "What is the primary force that opposes weight in flight?",
          options: ["Drag", "Thrust", "Lift", "Momentum"],
          correct: 2,
          explanation: "Lift is the aerodynamic force that acts perpendicular to the relative wind and opposes the weight of the aircraft."
        },
        {
          question: "What happens when thrust is greater than drag?",
          options: ["The aircraft climbs", "The aircraft accelerates", "The aircraft descends", "The aircraft turns"],
          correct: 1,
          explanation: "When thrust exceeds drag, the aircraft will accelerate in the direction of flight."
        },
        {
          question: "At what angle of attack does a stall typically occur?",
          options: ["10-12 degrees", "15-18 degrees", "20-25 degrees", "It varies by aircraft"],
          correct: 3,
          explanation: "The critical angle of attack varies by aircraft design, typically between 15-20 degrees for most general aviation aircraft."
        }
      ]
    }
  },
  lesson2: {
    title: "Lesson 2: Altimeter and Pressure",
    subtitle: "Understanding altitude readings and atmospheric pressure",
    flashcards: [
      { q: "What does 'From high to low, look out below' mean?", a: "When flying from high to low pressure areas, your true altitude is lower than indicated" },
      { q: "What does an altimeter read in cold air?", a: "Higher than true altitude - the aircraft is actually lower" },
      { q: "What is standard atmospheric pressure?", a: "29.92 inches of mercury (Hg) or 1013.25 millibars" },
      { q: "How often should you update altimeter setting?", a: "Every 100 nautical miles or when provided by ATC" },
      { q: "What are the four types of altitude?", a: "Indicated, Pressure, Density, and True altitude" },
      { q: "What is pressure altitude?", a: "The altitude shown when the altimeter is set to 29.92 inches Hg" },
      { q: "What affects density altitude?", a: "Temperature, pressure, and humidity - higher values decrease aircraft performance" },
      { q: "When is pressure altitude used?", a: "For flight level operations above 18,000 feet and performance calculations" }
    ],
    quiz: {
      questions: [
        {
          question: "In cold weather conditions, what does the altimeter indicate compared to true altitude?",
          options: ["Lower than true altitude", "Same as true altitude", "Higher than true altitude", "Varies randomly"],
          correct: 2,
          explanation: "In cold air, the altimeter reads higher than the actual altitude because cold air is denser, causing the aircraft to be lower than indicated."
        },
        {
          question: "What is pressure altitude?",
          options: ["Altitude shown on altimeter", "Altitude with 29.92 set", "True altitude above sea level", "Density altitude corrected"],
          correct: 1,
          explanation: "Pressure altitude is the altitude displayed when the altimeter is set to standard pressure (29.92 inches Hg)."
        }
      ]
    }
  },
  lesson3: {
    title: "Lesson 3: Weather Patterns",
    subtitle: "Meteorology fundamentals for pilots",
    flashcards: [
      { q: "What causes turbulence near mountains?", a: "Mountain waves and mechanical turbulence from wind flowing over terrain" },
      { q: "What is a cold front?", a: "A boundary where cold air mass advances and displaces warm air" },
      { q: "What weather is associated with cumulus clouds?", a: "Fair weather, possible afternoon thunderstorms if they develop vertically" },
      { q: "What is a warm front?", a: "A boundary where warm air gradually rises over cold air, creating layered clouds" },
      { q: "What clouds indicate possible icing conditions?", a: "Stratus, nimbostratus, and cumulonimbus clouds with visible moisture" },
      { q: "What is wind shear?", a: "A sudden change in wind speed or direction that can be dangerous during takeoff and landing" },
      { q: "How do you identify a thunderstorm?", a: "Towering cumulus or cumulonimbus clouds, often with anvil tops" },
      { q: "What is the most dangerous weather for small aircraft?", a: "Thunderstorms, icing, and severe turbulence" }
    ],
    quiz: {
      questions: [
        {
          question: "Which type of weather front typically produces the most severe weather?",
          options: ["Warm front", "Cold front", "Occluded front", "Stationary front"],
          correct: 1,
          explanation: "Cold fronts typically move faster and create more dramatic weather changes, often producing thunderstorms and severe weather."
        }
      ]
    }
  },
  lesson4: {
    title: "Lesson 4: Radio Communications",
    subtitle: "Aviation phraseology and communication procedures",
    flashcards: [
      { q: "What does 'Roger' mean in aviation?", a: "I have received and understood your transmission" },
      { q: "What is the phonetic alphabet for 'A'?", a: "Alpha" },
      { q: "When should you use 'Mayday'?", a: "In a life-threatening emergency requiring immediate assistance" }
    ],
    quiz: {
      questions: [
        {
          question: "What is the correct response when ATC says 'Contact tower on 118.1'?",
          options: ["Roger", "Contact tower 118.1", "118.1, good day", "Switching to tower 118.1"],
          correct: 0,
          explanation: "A simple 'Roger' acknowledges the instruction. You don't need to repeat the frequency back."
        }
      ]
    }
  },
  lesson5: {
    title: "Lesson 5: Navigation Systems",
    subtitle: "VOR, GPS, and pilotage fundamentals",
    flashcards: [
      { q: "What does VOR stand for?", a: "VHF Omnidirectional Range" },
      { q: "What is pilotage?", a: "Navigation by visual reference to landmarks" },
      { q: "What is dead reckoning?", a: "Navigation by computing position from course, speed, time, and wind" }
    ],
    quiz: {
      questions: [
        {
          question: "What navigation method relies on visual identification of landmarks?",
          options: ["Dead reckoning", "VOR navigation", "Pilotage", "GPS navigation"],
          correct: 2,
          explanation: "Pilotage is navigation by visual reference to landmarks on the ground."
        }
      ]
    }
  },
  lesson6: {
    title: "Lesson 6: Aircraft Systems",
    subtitle: "Engine, electrical, and fuel systems",
    flashcards: [
      { q: "What is carburetor ice?", a: "Ice formation in the carburetor that can block airflow and reduce power" },
      { q: "When is carburetor heat typically used?", a: "During descent, approach, and when carburetor ice is suspected" },
      { q: "What does the alternator do?", a: "Generates electrical power to charge the battery and power electrical systems" }
    ],
    quiz: {
      questions: [
        {
          question: "When should carburetor heat be applied?",
          options: ["Only during takeoff", "During climb", "During descent and approach", "Never in flight"],
          correct: 2,
          explanation: "Carburetor heat is typically used during descent and approach when power is reduced and ice formation is more likely."
        }
      ]
    }
  },
  lesson7: {
    title: "Lesson 7: Flight Controls",
    subtitle: "Primary and secondary flight controls",
    flashcards: [
      { q: "What are the three primary flight controls?", a: "Elevator, rudder, and ailerons" },
      { q: "What does the elevator control?", a: "Pitch attitude - nose up and nose down movement" },
      { q: "What are trim tabs used for?", a: "To reduce control pressure and maintain desired flight attitude" }
    ],
    quiz: {
      questions: [
        {
          question: "Which control surface is used to control yaw?",
          options: ["Elevator", "Ailerons", "Rudder", "Flaps"],
          correct: 2,
          explanation: "The rudder controls yaw, which is the left and right movement of the aircraft's nose."
        }
      ]
    }
  },
  lesson8: {
    title: "Lesson 8: Airport Operations",
    subtitle: "Traffic patterns and airport procedures",
    flashcards: [
      { q: "What is the standard traffic pattern direction?", a: "Left traffic (counterclockwise)" },
      { q: "What are the legs of a traffic pattern?", a: "Departure, crosswind, downwind, base, and final approach" },
      { q: "What is the purpose of CTAF?", a: "Common Traffic Advisory Frequency for pilot-to-pilot communication at uncontrolled airports" }
    ],
    quiz: {
      questions: [
        {
          question: "At an uncontrolled airport, what frequency is used for pilot announcements?",
          options: ["Tower frequency", "Ground control", "CTAF", "Emergency frequency"],
          correct: 2,
          explanation: "CTAF (Common Traffic Advisory Frequency) is used for pilot-to-pilot communication at uncontrolled airports."
        }
      ]
    }
  },
  lesson9: {
    title: "Lesson 9: Weight and Balance",
    subtitle: "Aircraft loading and center of gravity",
    flashcards: [
      { q: "What is the center of gravity?", a: "The point where the aircraft's weight is considered to be concentrated" },
      { q: "What happens if the CG is too far aft?", a: "The aircraft becomes unstable and difficult to recover from stalls" },
      { q: "What is useful load?", a: "The difference between maximum gross weight and empty weight" }
    ],
    quiz: {
      questions: [
        {
          question: "What is the result of loading an aircraft with the center of gravity too far forward?",
          options: ["Unstable flight", "Poor fuel economy", "Heavy elevator pressure", "All of the above"],
          correct: 2,
          explanation: "When the CG is too far forward, it requires heavy back pressure on the elevator to maintain level flight."
        }
      ]
    }
  },
  lesson10: {
    title: "Lesson 10: Emergency Procedures",
    subtitle: "Engine failures and emergency landings",
    flashcards: [
      { q: "What is the first action for engine failure after takeoff?", a: "Lower the nose to maintain best glide speed" },
      { q: "What is best glide speed?", a: "The airspeed that provides maximum gliding distance" },
      { q: "What does 'ABCD' stand for in emergencies?", a: "Airspeed, Best field, Checklist, Declare emergency" }
    ],
    quiz: {
      questions: [
        {
          question: "During an engine failure in flight, what is the pilot's first priority?",
          options: ["Radio for help", "Maintain best glide speed", "Restart the engine", "Find the nearest airport"],
          correct: 1,
          explanation: "The first priority is to maintain best glide speed to maximize gliding distance and time available for other actions."
        }
      ]
    }
  },
  lesson11: {
    title: "Lesson 11: Federal Aviation Regulations",
    subtitle: "Key regulations for private pilots",
    flashcards: [
      { q: "What is the minimum fuel reserve for VFR day flight?", a: "30 minutes of fuel remaining" },
      { q: "What are the VFR cloud clearance requirements?", a: "500 feet below, 1000 feet above, 2000 feet horizontal" },
      { q: "What is the minimum visibility for VFR flight?", a: "3 statute miles in most airspace" }
    ],
    quiz: {
      questions: [
        {
          question: "What is the minimum fuel reserve required for VFR day flights?",
          options: ["15 minutes", "30 minutes", "45 minutes", "1 hour"],
          correct: 1,
          explanation: "FAR 91.151 requires 30 minutes of fuel remaining for VFR day flights and 45 minutes for VFR night flights."
        }
      ]
    }
  }
};
